name: .NET Core CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        dotnet: ['2.2.7', '3.0.0-rc1']
    
    name: Build with dotnet ${{ matrix.dotnet }}
    
    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Build with dotnet
      run: dotnet build --configuration Release
